[package]
name = "nerd"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "image", "advanced", "svg"] }
tokio = { version = "1.44.1", features = ["full"] }
directories = "*"
